/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sockettcp;

import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;

/**
 *
 * @author frapi
 */
public class Tela extends javax.swing.JFrame {

    public Socket socket, socketArq;
    public DataOutputStream saida;
    public DataOutputStream arqSaida;
    public DataInputStream entrada;
    public DataInputStream arqEntrada;
    public String log="";
    /**
     * Creates new form ClienteMensagem
     *
     */
    public Tela(Socket socket, Socket socketArq) {
        initComponents();
        try {
            this.socket = socket;
            this.socketArq = socketArq;
            saida = new DataOutputStream(this.socket.getOutputStream());
            entrada = new DataInputStream(this.socket.getInputStream());
            arqSaida = new DataOutputStream(socketArq.getOutputStream());
            arqEntrada = new DataInputStream(socketArq.getInputStream());
           
            
            new Thread() {
                @Override
                public void run() {
                    while (true) {
                        try {
                            String mensagem = entrada.readUTF();
                            jtaMensagens.append(mensagem);
                            saveLog("->Usuario 2: "+mensagem);
                        } catch (IOException e) {
                            System.out.println(e.getMessage());
                        }
                    }
                }
            }.start();
            new Thread() {
                @Override
                public void run() {
                    while (true) {
                        try {
                            ReceberEscrever();
                            String mensagem = entrada.readUTF();
                            jtaMensagens.append(mensagem);
                            saveLog("->Usuario 2: "+mensagem);
                        } catch (IOException e) {
                            System.out.println(e.getMessage());
                        }
                    }
                }
            }.start();
            //FileWriter txt = new FileWriter("C:\\Users\\Public\\Documents\\mensagem.txt");
            //PrintWriter gravarTxt = new PrintWriter(txt);
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void lerEnviar(File caminho){
        try {
           FileInputStream br = new FileInputStream(caminho);
           arqSaida.writeUTF(caminho.getName());
           //arqSaida.write((int)caminho.length() );
           int c = 0;
           while((c= br.read())!=-1){
               //System.out.println(c);
               arqSaida.write(c);
           }
           br.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        
    }
    
    public void ReceberEscrever(){
        try{
            FileOutputStream bw = new FileOutputStream(arqEntrada.readUTF());
            //int tam = arqEntrada.read();
            int c=0;
            while((c=arqEntrada.read())!=-1){
                //System.out.println(c);
                bw.write(c);
            }
            bw.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void saveLog(String mensagem) {

        try {
            log = log + mensagem;
            File file = new File("log.txt");
            file.createNewFile();
            BufferedWriter fileW = new BufferedWriter(new FileWriter("log.txt"));
            fileW.write(log);
            fileW.close();
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void enviar(String mensagem) {
       
        try {
            
            saida.writeUTF(mensagem);
            jtaMensagens.append("\t\t\t" + mensagem);
            jtxtMensagem.setText("");
            saveLog("->Usuario 1: "+mensagem);

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
//    public void enviarArq(String caminho) { 
//        try {
//            
//            arqSaida.writeUTF(caminho);
//
//        } catch (IOException e) {
//            System.out.println(e.getMessage());
//        }
//    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtMensagem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMensagens = new javax.swing.JTextArea();
        jbArquivos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbEnviar.setText("Enviar");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("WhatsJava");

        jtxtMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtMensagemKeyPressed(evt);
            }
        });

        jtaMensagens.setColumns(20);
        jtaMensagens.setRows(5);
        jScrollPane1.setViewportView(jtaMensagens);

        jbArquivos.setText("Arquivos");
        jbArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbArquivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbArquivos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEnviar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbArquivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEnviar))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        String mensagem = jtxtMensagem.getText() + "\n";
        enviar(mensagem);
    }//GEN-LAST:event_jbEnviarActionPerformed

    private void jtxtMensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMensagemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String mensagem = jtxtMensagem.getText() + "\n";
            enviar(mensagem);
        }
    }//GEN-LAST:event_jtxtMensagemKeyPressed

    private void jbArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbArquivosActionPerformed
      
        JFileChooser fileC = new JFileChooser();
        int returnVal = fileC.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileC.getSelectedFile();
        String mensagem = "arq: " + file.getName() + "\n";
        enviar(mensagem);
//        System.out.println(file.getPath());
        lerEnviar(file);
        
    }

    }//GEN-LAST:event_jbArquivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbArquivos;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JTextArea jtaMensagens;
    private javax.swing.JTextField jtxtMensagem;
    // End of variables declaration//GEN-END:variables
}
